### ISSUE TITLE
Plugin Activation Breaks User Register Functionality

### ISSUE THREAD

**Issue by kylegce2** [BeycanPress/cryptocurrency-payments-for-paid-memberships-pro#5]
Hi BeycanPress, 

I noticed that straight-out-of-the-box when if I  _activate_ the CryptoPay Gateway for PMPro plugin version **1.0.7**, alongside CryptoPay Lite version **2.1.6**; then the user login and register functionality breaks for PMPro version **3.0.4**.

More specifically — if a user registers while CryptoPay Gateway is _**activated**_, any subsequent attempts to login with those credentials will fail.  Likewise, if CryptoPay Gateway is _**deactivated** during user registration, any subsequent attempts to login will succeed. 

I tried the following approach in my theme functions.php:
```
function runActivate() {
   activate_plugins( 'cryptocurrency-payments-for-paid-memberships-pro/cryptocurrency-payments-for-paid-memberships-pro.php' );
}

function runDeactivate() {
   deactivate_plugins( 'cryptocurrency-payments-for-paid-memberships-pro/cryptocurrency-payments-for-paid-memberships-pro.php' );
}

add_action('init', 'runDeactivate');
```
but failed to figure out how / where to activate the plugin when needed.

Any thouoghts?  Thanks for your attention

**Comment by 0xBeycan** [comment]
CryptoPay and this integration has no direct impact on user login or registration. The only complaint at the moment is that there is a login requirement at the checkout and there is no form there. We are working on that right now.
